// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// generate_spiral_cpp
NumericMatrix generate_spiral_cpp(double angle_start, double angle_end, int num_points);
RcppExport SEXP _spiralizer_generate_spiral_cpp(SEXP angle_startSEXP, SEXP angle_endSEXP, SEXP num_pointsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type angle_start(angle_startSEXP);
    Rcpp::traits::input_parameter< double >::type angle_end(angle_endSEXP);
    Rcpp::traits::input_parameter< int >::type num_points(num_pointsSEXP);
    rcpp_result_gen = Rcpp::wrap(generate_spiral_cpp(angle_start, angle_end, num_points));
    return rcpp_result_gen;
END_RCPP
}
// calculate_limits_cpp
NumericVector calculate_limits_cpp(NumericMatrix vertices, double padding);
RcppExport SEXP _spiralizer_calculate_limits_cpp(SEXP verticesSEXP, SEXP paddingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type vertices(verticesSEXP);
    Rcpp::traits::input_parameter< double >::type padding(paddingSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_limits_cpp(vertices, padding));
    return rcpp_result_gen;
END_RCPP
}
// count_bounded_cells_cpp
int count_bounded_cells_cpp(LogicalVector has_infinite);
RcppExport SEXP _spiralizer_count_bounded_cells_cpp(SEXP has_infiniteSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< LogicalVector >::type has_infinite(has_infiniteSEXP);
    rcpp_result_gen = Rcpp::wrap(count_bounded_cells_cpp(has_infinite));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_spiralizer_generate_spiral_cpp", (DL_FUNC) &_spiralizer_generate_spiral_cpp, 3},
    {"_spiralizer_calculate_limits_cpp", (DL_FUNC) &_spiralizer_calculate_limits_cpp, 2},
    {"_spiralizer_count_bounded_cells_cpp", (DL_FUNC) &_spiralizer_count_bounded_cells_cpp, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_spiralizer(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
