# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Generate Fermat Spiral Points (C++ Implementation)
#'
#' Fast C++ implementation of Fermat spiral point generation.
#' Uses vectorized operations and pre-allocation for optimal performance.
#'
#' @param angle_start Starting angle
#' @param angle_end Ending angle
#' @param num_points Number of points to generate
#' @return NumericMatrix with x,y coordinates
#' @export
generate_spiral_cpp <- function(angle_start, angle_end, num_points) {
    .Call('_spiralizer_generate_spiral_cpp', PACKAGE = 'spiralizer', angle_start, angle_end, num_points)
}

#' Calculate Plot Limits (C++ Implementation)
#'
#' Efficiently calculates the maximum absolute coordinate from a matrix.
#'
#' @param vertices NumericMatrix of vertex coordinates
#' @param padding Padding factor (e.g., 1.1 for 10% padding)
#' @return NumericVector with c(-limit, limit)
#' @export
calculate_limits_cpp <- function(vertices, padding = 1.1) {
    .Call('_spiralizer_calculate_limits_cpp', PACKAGE = 'spiralizer', vertices, padding)
}

#' Fast Bounded Cell Count
#'
#' Counts bounded cells by checking if all vertices are finite.
#' Much faster than R's Filter() for large cell counts.
#'
#' @param vertex_counts IntegerVector of vertex counts per cell
#' @param has_infinite LogicalVector indicating if cell has infinite vertices
#' @return Integer count of bounded cells
#' @export
count_bounded_cells_cpp <- function(has_infinite) {
    .Call('_spiralizer_count_bounded_cells_cpp', PACKAGE = 'spiralizer', has_infinite)
}

